### ISSUE TITLE
Holiday_Resort_Website review

### ISSUE THREAD

**Issue by Rumbie-Mudzie7** [MemoryTshipapu/Holiday_Resort_Website#1]
Great and impressive work on this project, however, it would be great if you would include the following in your code:

- [x] main, section and/or article HTML elements for a more semantic markup of each page.
- [x] improve your readme.MD by including contributions, project usage, screenshots of the project.
- [x] refer to [https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/](URL) for a better understanding of writing a good readme.MD file.

**Comment by MemoryTshipapu** [comment]
Thank you so much for your comments. I have updated the readme file and inserted the necessary elements to make my code more readable.
